spring:
  datasource:
    url: jdbc:mysql://118.178.255.173:3306/pinxv?serverTimezone=Asia/Shanghai&characterEncoding=utf8mb4
    username: pinxv
    password: hackathon2020
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
